name: Publish Resume

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0")
          echo "Latest Tag: $LATEST_TAG"
          echo "current_version=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Increment Version
        id: increment_version
        run: |
          VERSION=$(echo "${{ steps.get_tag.outputs.current_version }}" | sed 's/^v//')
          echo "Current Version: $VERSION"
          NEXT_VERSION=$((VERSION + 1))
          NEXT_TAG="v$NEXT_VERSION"
          echo "Next Tag: $NEXT_TAG"
          echo "version=$NEXT_TAG" >> $GITHUB_OUTPUT

      - name: Compile Modular Version
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: false

      - name: Rename Modular PDF
        run: mv main.pdf Ayush_Jaipuriyar_Resume.pdf

      - name: Compile Single-File Version
        uses: xu-cheng/latex-action@v4
        with:
          root_file: Ayush_Jaipuriyar_single_file.tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: false

      - name: Rename Single-File PDF
        run: mv Ayush_Jaipuriyar_single_file.pdf Ayush_Jaipuriyar_Single_File_Resume.pdf

      - name: Check PDFs exist
        run: |
          if [ ! -f Ayush_Jaipuriyar_Resume.pdf ]; then
            echo "Modular PDF not generated"
            exit 1
          fi
          if [ ! -f Ayush_Jaipuriyar_Single_File_Resume.pdf ]; then
            echo "Single-file PDF not generated"
            exit 1
          fi

      - name: Tag the release
        run: |
          new_tag=${{ steps.increment_version.outputs.version }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag $new_tag
          git push origin $new_tag

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.version }}
          files: |
            Ayush_Jaipuriyar_Resume.pdf
            Ayush_Jaipuriyar_Single_File_Resume.pdf
            main.tex
            sections/*.tex
            Ayush_Jaipuriyar_single_file.tex

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          include_files: |
            Ayush_Jaipuriyar_Resume.pdf
            Ayush_Jaipuriyar_Single_File_Resume.pdf
